  name: challenge 5

  on:
    workflow_dispatch:
    workflow_call:
      inputs:
        environment:
        description: 'The name of the environment, e.g. dev, test prod'
        default: 'dev'
        required: true
        type: string
  env:
    WORKING_DIRECTORY: "wth-team14"
  jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
            # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ./InfrastructureAsCode/main.bicep
          #parameters: ''
          failOnStdErr: false
                      
                        
    

    
        
