  name: challenge 4

  on:
    workflow_dispatch:

  jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
        - name: step1
          uses: azure/login@v1
          with: 
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Deploy Azure Resource Manager (ARM) Template
          uses: Azure/arm-deploy@v1.0.9
        
          with:
            scope: 
            resourceGroupName:  ${{ vars.RESOURCE_GROUP_NAME }}
            template: 
            deploymentMode: # optional
            deploymentName: # optional
            parameters: # optional
            failOnStdErr: # optional, default is true
            additionalArguments: # optional
                      
                        
    

    
        
